server {
    # Port 80 pe suno — HTTP ka default port yahi hai
    listen 80;

    # Static files serve karo
    # Jab bhi koi / pe aaye — index.html do
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Agar file nahi mili toh index.html do
        try_files $uri $uri/ /index.html;
    }

    # /api/ wali saari requests FastAPI ko bhejo
    # Browser sochta hai nginx se baat kar raha hai
    # Actually nginx FastAPI ko forward kar deta hai
    location /api/ {
        proxy_pass http://fastapi-service:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
