apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1              # 1 copy of MongoDB
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6.0   # Official MongoDB image
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: studentsdb

